FROM openjdk:8-jre-alpine
MAINTAINER cesar.rodriguez@pragma.com.co
ADD build/libs/mongo-test-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 7800
ENTRYPOINT ["java", "-Dspring.profiles.active=dev", "-jar", "/app.jar"]